# Camera:
[camera]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0]
near_far = [0.1, 100.0]
fov = 90.0

# Materials:
[[materials]]
color = [1.0, 0.3, 0.2]
attenuation = [0.2,0.2,0.2]
roughness = 0.0
emission = 0.0
ior = 0.0

# Spheres:
[[spheres]]
position = [0.0, 0.0, -2.0]
radius = 1.0
material_id = 0
texture_id = [-1, -1, -1]