# Camera:
[camera]
position = [0.0, 2.0, 5.0]
rotation = [0.0, 0.0]
near_far = [0.1, 100.0]
fov = 90.0

# Materials:
[[materials]] # Ground
color = [0.8, 0.8, 0.8]
attenuation = [0.0,0.0,0.0]
roughness = 0.0
emission = 10.0
ior = 0.0

[[materials]]
color = [0.3, 1.0, 0.2]
attenuation = [0.2,0.2,0.2]
roughness = 0.0
emission = 0.0
ior = 0.0

[[materials]] # Glass Sphere
color = [1.0, 1.0, 1.0]
attenuation = [1.0,1.0,1.0]
roughness = 0.0
emission = 0.0
ior = 1.5

[[materials]] # "Air bubble in Sphere"
color = [1.0, 1.0, 1.0]
attenuation = [1.0,1.0,1.0]
roughness = 0.0
emission = 0.0
ior = 0.5 # Lower IOR than the sphere

[[materials]] # "White Bachground Material for Textures"
color = [1.0, 1.0, 1.0]
attenuation = [0.2,0.2,0.2]
roughness = 0.5
emission = 0.0
ior = 0.0

[[textures]]
diffuse = "examples/4-complex_material/res/pavement_26_basecolor-1K.png"
normal = "examples/4-complex_material/res/pavement_26_normal-1K.png"
roughness = "examples/4-complex_material/res/pavement_26_roughness-1K.png"

[[textures]]
diffuse = "examples/4-complex_material/res/others_0035_color_1k.jpg"
normal = "examples/4-complex_material/res/others_0035_normal_directx_1k.png"
roughness = "examples/4-complex_material/res/others_0035_roughness_1k.jpg"

# Spheres:
[[spheres]] # Light
position = [0.0, 8.7, 0.0]
radius = 3.0
material_id = 0
texture_id = [-1, -1, -1]

[[spheres]]
position = [2.0, 1.3, 1.3]
radius = 1.0
material_id = 1
texture_id = [-1, -1, -1]

[[spheres]] # Glass Sphere
position = [1.0, 1.3, -1.3]
radius = 1.0
material_id = 2
texture_id = [-1, -1, -1]


[3d_model_paths]
gltf_path = "examples/5-cornell_box/res/cornell_box.glb"

